<?php
$config['Permissions'] =  array(
					'dummy' => array(
								'Pages' 					=> array(),
								'Users' 					=> array(),
								'Members' 				=> array(),
								'Teams' 					=> array(),
								'Teammembers' 		=> array(),
								'Games' 					=> array(),
								'Trainings' 			=> array(),
								'Trainingmoments' => array(),
								'Efforts' 				=> array(),
								'Newsitems' 			=> array(),
								'Pictures' 				=> array(),
								'Uploads' 				=> array(),
								'Mailings'				=> array(),
								'Mails'						=> array(),
								'Posts'						=> array(),
								'Comments' 				=> array(),
								'Meterings' 			=> array(),
								'Reports' 				=> array(),
								'Events'					=> array(),
								'Subscriptions'		=> array(),
								'Enquetes' 				=> array()
								),
					'admin' => array(
								'Pages'						=> array('index' => 1, 'view' => 1, 'add' => 1, 'edit' => 1, 'delete' => 1, 'display' => 1),
								'Users'						=> array('index' => 1, 'view' => 1, 'add' => 1, 'edit' => 1, 'delete' => 1, 'reports' => 1, 'logout' => 1, 'changepassword' => 1, 'profile' => 1),
								'Members'					=> array('index' => 1, 'view' => 1, 'add' => 1, 'edit' => 1, 'delete' => 1, 'reports' => 1, 'filter' => 1, 'editfinance' => 1, 'reactivate' => 1, 'inactivate' => 1, 'linkpictures' => 1, 'unlinkpictures' => 1, 'birthdays' => 1, 'ajbirthdaypublic' => 1, 'import' => 1, 'uploadCsv' => 1),
								'Teams'						=> array('index' => 1, 'view' => 1, 'add' => 1, 'edit' => 1, 'delete' => 1, 'reports' => 1, 'viewnew' => 1, 'overview' => 1, 'viewlicenses' => 1, 'listing' => 1, 'list_for_trainers' => 1),
								'Teammembers'			=> array('index' => 1, 'view' => 1, 'add' => 1, 'edit' => 1, 'delete' => 1, 'team' => 1, 'dashboard' => 1, 'feed' => 1, 'addbulk' => 1, 'listing' => 1),
								'Games'						=> array('index' => 1, 'view' => 1, 'add' => 1, 'edit' => 1, 'delete' => 1, 'reports' => 1, 'team' => 1, 'presences' => 1, 'overview' => 1, 'shortoverview' => 1, 'teamtable' => 1, 'import' => 1, 'fortasks' => 1),
								'Trainings'				=> array('index' => 1, 'view' => 1, 'add' => 1, 'edit' => 1, 'delete' => 1, 'team' => 1, 'presences' => 1, 'listperiod' => 1, 'generate' => 1),
								'Trainingmoments'	=> array('index' => 1, 'view' => 1, 'add' => 1, 'edit' => 1, 'delete' => 1),
								'Efforts'					=> array('index' => 1, 'view' => 1, 'add' => 1, 'edit' => 1, 'delete' => 1, 'reports' => 1, 'listmember' => 1, 'listteam' => 1, 'periodicoverview' => 1, 'ajfetchperiod' => 1),
								'Newsitems'				=> array('index' => 1, 'view' => 1, 'add' => 1, 'edit' => 1, 'delete' => 1, 'redactie' => 1, 'fetch' => 1, 'listsocial' => 1, 'editsocial' => 1, 'setstatus' => 1),
								'Pictures'				=> array('index' => 1, 'view' => 1, 'add' => 1, 'edit' => 1, 'delete' => 1, 'category' => 1),
								'Uploads'					=> array('index' => 1, 'view' => 1, 'add' => 1, 'edit' => 1, 'delete' => 1, 'reports' => 1, 'category' => 1),
								'Mailings'				=> array('index' => 1, 'view' => 1, 'add' => 1, 'edit' => 1, 'delete' => 1),
								'Mails'						=> array('index' => 1, 'view' => 1, 'add' => 1, 'edit' => 1, 'delete' => 1),
								'Posts'						=> array('index' => 1, 'view' => 1, 'add' => 1, 'edit' => 1, 'delete' => 1),
								'Comments'				=> array('index' => 1, 'view' => 1, 'add' => 1, 'edit' => 1, 'delete' => 1),
								'Meterings'				=> array('index' => 1, 'view' => 1, 'add' => 1, 'edit' => 1, 'delete' => 1),
								'Reports'					=> array('index' => 1, 'view' => 1, 'add' => 1, 'edit' => 1, 'delete' => 1, 'reports' => 1, 'members' => 1, 'members4trainers' => 1, 'members4mgmt' => 1, 'memberscomplete' => 1, 'membersbirthday' => 1, 'memberspread' => 1, 'mailmerge' => 1, 'efforts' => 1, 'presencestrainings' => 1, 'presencesgames' => 1, 'presencesallgames' => 1, 'presencesalltrainings' => 1, 'usersperrole' => 1),
								'Events'					=> array('index' => 1, 'view' => 1, 'add' => 1, 'edit' => 1, 'delete' => 1),
								'Subscriptions'		=> array('index' => 1, 'view' => 1, 'add' => 1, 'edit' => 1, 'delete' => 1, 'listevent' => 1),
								'Enquetes'				=> array('index' => 1, 'view' => 1, 'add' => 1, 'edit' => 1, 'delete' => 1, 'generate' => 1, 'lijst' => 1, 'toon' => 1, 'toon_formulier' => 1, 'toon_vrijetekst' => 1, 'export' => 1)
								),
					'memberadmin' => array(
								'Pages'						=> array('display' => 1),
								'Users'						=> array('logout' => 1, 'changepassword' => 1, 'profile' => 1),
								'Members'					=> array('index' => 1, 'view' => 1, 'add' => 1, 'edit' => 1, 'reports' => 1, 'filter' => 1, 'editfinance' => 1, 'reactivate' => 1, 'inactivate' => 1, 'linkpictures' => 1, 'unlinkpictures' => 1, 'birthdays' => 1, 'ajbirthdaypublic' => 1, 'import' => 1),
								'Teams'						=> array('index' => 1, 'view' => 1),
								'Teammembers'			=> array('index' => 1, 'view' => 1),
								'Games'						=> array('index' => 1, 'view' => 1, 'team' => 1),
								'Trainings'				=> array('index' => 1, 'view' => 1, 'team' => 1),
								'Trainingmoments' => array('index' => 0, 'view' => 0, 'add' => 0, 'edit' => 0, 'delete' => 0),
								'Efforts'					=> array(),
								'Newsitems'				=> array(),
								'Pictures'				=> array('index' => 1, 'view' => 1, 'add' => 1, 'edit' => 1, 'category' => 1),
								'Uploads'					=> array('index' => 1, 'view' => 1, 'add' => 1, 'edit' => 1, 'reports' => 1, 'category' => 1),
								'Mailings'				=> array('index' => 1, 'view' => 1),
								'Mails'						=> array('index' => 1, 'view' => 1),
								'Posts'						=> array('index' => 1, 'view' => 1, 'add' => 1),
								'Comments'				=> array('index' => 1, 'view' => 1, 'add' => 1),
								'Meterings'				=> array('index' => 1, 'view' => 1),
								'Reports'					=> array('members' => 1, 'members4trainers' => 1, 'members4mgmt' => 1, 'memberscomplete' => 1, 'memberspread' => 1, 'mailmerge' => 1),
								'Events'					=> array(),
								'Subscriptions'		=> array('listevent' => 1),
								'Enquetes'				=> array()
								),
					'teamadmin' => array(
								'Pages'						=> array('display' => 1),
								'Users'						=> array('logout' => 1, 'changepassword' => 1, 'profile' => 1),
								'Members'					=> array('index' => 1, 'view' => 1, 'quickadd' => 1, 'reports' => 1),
								'Teams'						=> array('index' => 1, 'view' => 1, 'add' => 1, 'edit' => 1, 'reports' => 1, 'viewnew' => 1, 'overview' => 1, 'viewlicenses' => 1, 'listing' => 1, 'list_for_trainers' => 1),
								'Teammembers'			=> array('index' => 1, 'view' => 1, 'add' => 1, 'edit' => 1, 'team' => 1, 'dashboard' => 1, 'feed' => 1, 'addbulk' => 1, 'listing' => 1),
								'Games'						=> array('index' => 1, 'view' => 1, 'add' => 1, 'edit' => 1, 'delete' => 1, 'team' => 1, 'presences' => 1, 'overview' => 1, 'shortoverview' => 1, 'teamtable' => 1, 'import' => 1),
								'Trainings'				=> array('index' => 1, 'view' => 1, 'add' => 1, 'edit' => 1, 'delete' => 1, 'team' => 1, 'presences' => 1, 'listperiod' => 1, 'generate' => 1),
								'Trainingmoments'	=> array('index' => 1, 'view' => 1, 'add' => 1, 'edit' => 1, 'delete' => 1),
								'Efforts'					=> array('index' => 1, 'view' => 1, 'add' => 1, 'edit' => 1, 'listmember' => 1, 'listteam' => 1),
								'Newsitems'				=> array(),
								'Pictures'				=> array('index' => 1, 'view' => 1, 'add' => 1, 'edit' => 1, 'category' => 1),
								'Uploads'					=> array('index' => 1, 'view' => 1, 'add' => 1, 'edit' => 1, 'reports' => 1, 'category' => 1),
								'Mailings'				=> array('index' => 1, 'view' => 1),
								'Mails'						=> array('index' => 1, 'view' => 1),
								'Posts'						=> array('index' => 1, 'view' => 1, 'add' => 1),
								'Comments'				=> array('index' => 1, 'view' => 1, 'add' => 1),
								'Meterings'				=> array('index' => 1),
								'Reports'					=> array('index' => 1, 'members' => 1, 'members4trainers' => 1, 'presencestrainings' => 1, 'presencesgames' => 1, 'presencesallgames' => 1, 'presencesalltrainings' => 1),
								'Events'					=> array(),
								'Subscriptions'		=> array(),
								'Enquetes'				=> array()
								),
					'gameadmin' => array(
								'Pages'						=> array('display' => 1),
								'Users'						=> array('logout' => 1, 'changepassword' => 1, 'profile' => 1),
								'Members'					=> array('index' => 1, 'view' => 1, 'reports' => 1),
								'Teams'						=> array('index' => 1, 'view' => 1, 'overview' => 1, 'viewlicenses' => 1, 'list_for_trainers' => 1),
								'Teammembers'			=> array('index' => 1, 'view' => 1, 'team' => 1, 'dashboard' => 1),
								'Games'						=> array('index' => 1, 'view' => 1, 'add' => 1, 'edit' => 1, 'reports' => 1, 'team' => 1, 'overview' => 1, 'shortoverview' => 1, 'teamtable' => 1, 'import' => 1, 'fortasks' => 1),
								'Trainings'				=> array('index' => 1, 'view' => 1, 'team' => 1, 'listperiod' => 1),
								'Trainingmoments' => array(),
								'Efforts'					=> array(),
								'Newsitems'				=> array(),
								'Pictures'				=> array('index' => 1, 'view' => 1, 'add' => 1, 'edit' => 1, 'category' => 1),
								'Uploads'					=> array('index' => 1, 'view' => 1, 'add' => 1, 'edit' => 1),
								'Mailings'				=> array('index' => 1, 'view' => 1),
								'Mails'						=> array('index' => 1, 'view' => 1),
								'Posts'						=> array('index' => 1, 'view' => 1, 'add' => 1),
								'Comments'				=> array('index' => 1, 'view' => 1, 'add' => 1),
								'Meterings'				=> array('index' => 1),
								'Reports'					=> array('members' => 1, 'members4trainers' => 1, 'membersbirthday' => 1, 'memberspread' => 1),
								'Events'					=> array(),
								'Subscriptions'		=> array(),
								'Enquetes'				=> array()
								),
					'trainerfinance' => array(
								'Pages'						=> array('display' => 1),
								'Users'						=> array('logout' => 1, 'changepassword' => 1, 'profile' => 1),
								'Members'					=> array('index' => 1, 'view' => 1, 'reports' => 1, 'filter' => 1, 'payroll' => 1),
								'Teams'						=> array('index' => 1, 'view' => 1),
								'Teammembers'			=> array('index' => 1, 'view' => 1, 'team' => 1),
								'Games'						=> array('index' => 1, 'view' => 1, 'team' => 1, 'overview' => 1, 'teamtable' => 1),
								'Trainings'				=> array('index' => 1, 'view' => 1, 'team' => 1, 'listperiod' => 1),
								'Trainingmoments' => array('index' => 0, 'view' => 0, 'add' => 0, 'edit' => 0, 'delete' => 0),
								'Efforts'					=> array('index' => 1, 'view' => 1, 'add' => 1, 'reports' => 1, 'listmember' => 1, 'listteam' => 1, 'periodicoverview' => 1, 'ajfetchperiod' => 1),
								'Newsitems'				=> array(),
								'Pictures'				=> array(),
								'Uploads'					=> array('index' => 1, 'view' => 1, 'add' => 1, 'edit' => 1),
								'Mailings'				=> array('index' => 1, 'view' => 1),
								'Mails'						=> array('index' => 1, 'view' => 1),
								'Posts'						=> array('index' => 1, 'view' => 1, 'add' => 1),
								'Comments'				=> array('index' => 1, 'view' => 1, 'add' => 1),
								'Meterings'				=> array(),
								'Reports'					=> array('members' => 1, 'members4mgmt' => 1, 'memberspread' => 1, 'efforts' => 1),
								'Events'					=> array(),
								'Subscriptions'		=> array(),
								'Enquetes'				=> array()
								),
					'memberfinance' => array(
								'Pages'						=> array('display' => 1),
								'Users'						=> array('logout' => 1, 'changepassword' => 1, 'profile' => 1),
								'Members'					=> array('index' => 1, 'view' => 1, 'edit' => 1, 'reports' => 1, 'filter' => 1, 'editfinance' => 1),
								'Teams'						=> array('index' => 1, 'view' => 1),
								'Teammembers'			=> array('index' => 1, 'view' => 1),
								'Games'						=> array('index' => 1, 'view' => 1),
								'Trainings'				=> array('index' => 1, 'view' => 1),
								'Trainingmoments' => array('index' => 0, 'view' => 0, 'add' => 0, 'edit' => 0, 'delete' => 0),
								'Efforts'					=> array(),
								'Newsitems'				=> array(),
								'Pictures'				=> array(),
								'Uploads'					=> array('index' => 1, 'view' => 1, 'add' => 1, 'edit' => 1),
								'Mailings'				=> array('index' => 1, 'view' => 1),
								'Mails'						=> array('index' => 1, 'view' => 1),
								'Posts'						=> array('index' => 1, 'view' => 1, 'add' => 1),
								'Comments'				=> array('index' => 1, 'view' => 1, 'add' => 1),
								'Meterings'				=> array(),
								'Reports'					=> array('members' => 1, 'members4trainers' => 1, 'members4mgmt' => 1, 'memberspread' => 1),
								'Events'					=> array(),
								'Subscriptions'		=> array(),
								'Enquetes'				=> array()
								),
					'memberedit' => array(
								'Pages'						=> array('display' => 1),
								'Users'						=> array('logout' => 1, 'changepassword' => 1, 'profile' => 1),
								'Members'					=> array('index' => 1, 'view' => 1, 'edit' => 1, 'reports' => 1, 'filter' => 1, 'editfinance' => 1, 'inactivate' => 1),
								'Teams'						=> array('index' => 1, 'view' => 1),
								'Teammembers'			=> array('index' => 1, 'view' => 1),
								'Games'						=> array('index' => 1, 'view' => 1),
								'Trainings'				=> array('index' => 1, 'view' => 1),
								'Trainingmoments' => array('index' => 0, 'view' => 0, 'add' => 0, 'edit' => 0, 'delete' => 0),
								'Efforts'					=> array(),
								'Newsitems'				=> array(),
								'Pictures'				=> array(),
								'Uploads'					=> array('index' => 1, 'view' => 1),
								'Mailings'				=> array('index' => 1, 'view' => 1),
								'Mails'						=> array('index' => 1, 'view' => 1),
								'Posts'						=> array('index' => 1, 'view' => 1),
								'Comments'				=> array('index' => 1, 'view' => 1),
								'Meterings'				=> array(),
								'Reports'					=> array('members' => 1, 'members4trainers' => 1, 'members4mgmt' => 1, 'memberspread' => 1),
								'Events'					=> array(),
								'Subscriptions'		=> array('listevent' => 1),
								'Enquetes'				=> array()
								),
					'memberview' => array(
								'Pages'						=> array('display' => 1),
								'Users'						=> array('logout' => 1, 'changepassword' => 1, 'profile' => 1),
								'Members'					=> array('index' => 1, 'view' => 1, 'reports' => 1, 'filter' => 1),
								'Teams'						=> array('index' => 1, 'view' => 1, 'overview' => 1, 'viewlicenses' => 1),
								'Teammembers'			=> array('index' => 1, 'view' => 1),
								'Games'						=> array('index' => 1, 'view' => 1),
								'Trainings'				=> array('index' => 1, 'view' => 1),
								'Trainingmoments' => array('index' => 0, 'view' => 0, 'add' => 0, 'edit' => 0, 'delete' => 0),
								'Efforts'					=> array(),
								'Newsitems'				=> array(),
								'Pictures'				=> array(),
								'Uploads'					=> array('index' => 1, 'view' => 1),
								'Mailings'				=> array('index' => 1, 'view' => 1),
								'Mails'						=> array('index' => 1, 'view' => 1),
								'Posts'						=> array('index' => 1, 'view' => 1),
								'Comments'				=> array('index' => 1, 'view' => 1),
								'Meterings'				=> array(),
								'Reports'					=> array('members' => 1, 'members4trainers' => 1, 'members4mgmt' => 1, 'memberspread' => 1, 'presencestrainings' => 1, 'presencesgames' => 1),
								'Events'					=> array(),
								'Subscriptions'		=> array('listevent' => 1),
								'Enquetes'				=> array()
								),
					'trainer' => array(
								'Pages'						=> array('display' => 1),
								'Users'						=> array('logout' => 1, 'changepassword' => 1, 'profile' => 1),
								'Members'					=> array('index' => 1, 'view' => 1),
								'Teams'						=> array('index' => 1, 'view' => 1, 'overview' => 1, 'viewlicenses' => 1, 'list_for_trainers' => 1),
								'Teammembers'			=> array('index' => 1, 'view' => 1, 'team' => 1, 'dashboard' => 1, 'feed' => 1),
								'Games'						=> array('index' => 1, 'view' => 1, 'add' => 1, 'team' => 1, 'presences' => 1, 'overview' => 1, 'shortoverview' => 1, 'teamtable' => 1),
								'Trainings'				=> array('index' => 1, 'view' => 1, 'add' => 1, 'edit' => 1, 'team' => 1, 'presences' => 1, 'listperiod' => 1),
								'Trainingmoments' => array('index' => 0, 'view' => 0, 'add' => 0, 'edit' => 0, 'delete' => 0),
								'Efforts'					=> array('index' => 1, 'view' => 1, 'add' => 1, 'edit' => 1, 'listmember' => 1, 'listteam' => 1),
								'Newsitems'				=> array(),
								'Pictures'				=> array('view' => 1, 'add' => 1, 'category' => 1),
								'Uploads'					=> array('index' => 1, 'view' => 1, 'add' => 1, 'edit' => 1, 'reports' => 1, 'category' => 1),
								'Mailings'				=> array(),
								'Mails'						=> array(),
								'Posts'						=> array('index' => 1, 'view' => 1, 'add' => 1),
								'Comments'				=> array('index' => 1, 'view' => 1, 'add' => 1),
								'Meterings'				=> array('index' => 1),
								'Reports'					=> array('members4trainers' => 1, 'presencestrainings' => 1, 'presencesgames' => 1),
								'Events'					=> array(),
								'Subscriptions'		=> array(),
								'Enquetes'				=> array()
								),
					'member' => array(
								'Pages'						=> array('display' => 1, 'view' => 1),
								'Users'						=> array('logout' => 1, 'changepassword' => 1, 'profile' => 1),
								'Members'					=> array(),
								'Teams'						=> array('index' => 1, 'view' => 1),
								'Teammembers'			=> array('index' => 1, 'view' => 1),
								'Games'						=> array('index' => 1, 'view' => 1),
								'Trainings'				=> array('index' => 1, 'view' => 1),
								'Trainingmoments' => array('index' => 0, 'view' => 0, 'add' => 0, 'edit' => 0, 'delete' => 0),
								'Efforts'					=> array(),
								'Newsitems'				=> array(),
								'Pictures'				=> array(),
								'Uploads'					=> array(),
								'Mailings'				=> array(),
								'Mails'						=> array(),
								'Posts'						=> array('index' => 1, 'view' => 1, 'add' => 1),
								'Comments'				=> array('index' => 1, 'view' => 1, 'add' => 1),
								'Meterings'				=> array(),
								'Reports'					=> array(),
								'Events'					=> array(),
								'Subscriptions'		=> array(),
								'Enquetes'				=> array()
								)
			);
